name: Push Docker Image

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Build
        run: docker build --tag ghcr.io/cirruslabs/google-storage-proxy:latest .
      - name: Docker Login
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Docker Push
        run: docker push ghcr.io/cirruslabs/google-storage-proxy:latest